In [1]:
import pandas as pd
import json
import requests
from bs4 import BeautifulSoup
import scipy as sp
import numpy as np
import pandas as pd
from datetime import datetime
import pandas_profiling

# Foursquare

Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [2]:
city_stations = pd.read_csv('newnyc_bike.csv')
lat = city_stations['latitude']
long = city_stations['longitude']

In [3]:
api_key = "fsq3k78pfxFiUUkKIN593+jFRQc8dNWV5REu+zI5c8FX1Ts="
fields = 'fsq_id,name,geocodes,categories,distance,rating,hours,hours_popular,popularity,features'

headers = {
      "accept": "application/json",
      "Authorization": api_key
}
#fsq_url = 'https://api.foursquare.com/v3/places/search?query=restaurant&ll={lat[i]},{long[i]}&fields={fields}&radius=1000&limit=50'
fsq_url = (f'https://api.foursquare.com/v3/places/search?categories=13000&fields={fields}&radius=1000&&limit=50')
  
restaurants = requests.get(fsq_url, headers=headers).json()

In [4]:
lat_fsquare=[]
long_fsquare=[]
for i in range(len(lat)):
    lat_fsquare.append(restaurants)
for h in range(len(long)):
    long_fsquare.append(restaurants)

In [5]:
api_key = "fsq3k78pfxFiUUkKIN593+jFRQc8dNWV5REu+zI5c8FX1Ts="
fields = 'fsq_id,name,geocodes,categories,distance,rating,hours,hours_popular,popularity,features'

headers = {
      "accept": "application/json",
      "Authorization": api_key
}
#fsq_url = 'https://api.foursquare.com/v3/places/search?query=restaurant&ll={lat[i]},{long[h]}&fields={fields}&radius=1000&limit=50'
fsq_url = (f'https://api.foursquare.com/v3/places/search?ll={lat[i]},{long[h]}&categories=13000&fields={fields}&radius=1000&&limit=50')
  
restaurants = requests.get(fsq_url, headers=headers).json()

In [ ]:
restaurants

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [8]:
def restaurantPOI(lat,long):
    list_of_dict=[]   
    for x in restaurants['results']:
        categories = x.get('categories', None)
        cat_id = categories[0]['id'] if len(categories) > 0 else None
        category_name = categories[0]['name'] if len(categories) > 0 else None
        
        poi_dict = {
            'lat_long':f'{lat},{long}',
            'fsq_id':x['fsq_id'],
            'cat_id': cat_id,
            'category_name': category_name,
            'categories': categories,
            'name': x.get('name', None),
            'distance': x.get('distance', None),
            'latitude': x.get('geocodes',{}).get('main',{}).get('latitude',None),
            'longtitude': x.get('geocodes',{}).get('main',{}).get('longtitude',None),
            'address': x.get('location',{}).get('formatted_address', None),
            'popularity': x.get('popularity', None),
            'open_now': x.get('hours',{}).get('open_now', None),
            'rating': x.get('rating', None),
            'rating_count': x.get('stats',{}).get('total_ratings', None),
            'my_timestamp': datetime.now()
        }
        list_of_dict.append(poi_dict)
    return pd.DataFrame(list_of_dict)

Put your parsed results into a DataFrame

In [ ]:
restaurantPOI(40.795000,-73.964500)

In [10]:
restaurant_data = restaurantPOI(40.795000,-73.964500)

In [11]:
restaurant_data.to_csv('restaurants_data4.csv', index=False)

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [12]:
city_stations = pd.read_csv('newnyc_bike.csv')
lat1 = city_stations['latitude']
long1 = city_stations['longitude']

In [13]:
import requests

url = "https://api.yelp.com/v3/businesses/search?ll={lat[i]},{long[h]}&radius=1000&categories=restaurant&sort_by=best_match&limit=50"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer qY5lS21jT2H2StwPxQTvQh_1fK6nCd_a5aO8lNcSt7LcKf7o0T1GDc-2GHujfXy3gerjdhlIu3naC9M7RoQW8Xg0fcdWRjbRkZTSrK3BPIFMrTgMbYbUUfN5zkCMY3Yx"
}
yelp_restaurant = requests.get(url, headers=headers)

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [14]:
lat_fsquare=[]
long_fsquare=[]
for i in range(len(lat)):
    lat_fsquare.append(yelp_restaurant)
for h in range(len(long)):
    long_fsquare.append(yelp_restaurant)

In [16]:
def restaurantPOI2(lat1,long1):
    list_of_dict=[]   
    for yelp in restaurants['results']:
        categories = yelp.get('categories', None)
        cat_id = categories[0]['id'] if len(categories) > 0 else None
        category_name = categories[0]['name'] if len(categories) > 0 else None
        
        yelp_dict = {
            'lat_long':f'{lat1},{long1}',
            'fsq_id':yelp['fsq_id'],
            'cat_id': cat_id,
            'category_name': category_name,
            'categories': categories,
            'name': yelp.get('name', None),
            'distance': yelp.get('distance', None),
            'latitude': yelp.get('geocodes',{}).get('main',{}).get('latitude',None),
            'longtitude': yelp.get('geocodes',{}).get('main',{}).get('longtitude',None),
            'address': yelp.get('location',{}).get('formatted_address', None),
            'popularity': yelp.get('popularity', None),
            'open_now': yelp.get('hours',{}).get('open_now', None),
            'rating': yelp.get('rating', None),
            'rating_count': yelp.get('stats',{}).get('total_ratings', None),
            'my_timestamp': datetime.now()
        }
        list_of_dict.append(yelp_dict)
    return pd.DataFrame(list_of_dict)

Put your parsed results into a DataFrame

In [ ]:
restaurantPOI2(40.795000,-73.964500)

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

# Foursquare API provide a more complet data than Yelp API

Get the top 10 restaurants according to their rating

In [18]:
# go down 1 level to 'results'
top_restaurants = restaurants['results']

In [ ]:
top_restaurants

In [19]:
rating_restaurants = pd.json_normalize(top_restaurants)

In [ ]:
rating_restaurants.keys()

In [21]:
top_rating = rating_restaurants.sort_values(by= 'rating', ascending = False)

In [22]:
top_rating.head(10)

,fsq_id,categories,distance,hours_popular,name,popularity,rating,features.payment.credit_cards.accepts_credit_cards,features.food_and_drink.alcohol.beer,features.food_and_drink.alcohol.byo,...,features.amenities.parking.parking,features.amenities.parking.street_parking,features.amenities.parking.private_lot,features.services.dine_in.groups_only_reservations,features.amenities.parking.valet_parking,features.amenities.parking.public_lot,features.payment.digital_wallet.accepts_nfc,features.services.dine_in.online_reservations,features.food_and_drink.meals.dessert,features.amenities.coat_check
31,56bf8899cd102af95de0a66e,"[{'id': 13068, 'name': 'American Restaurant', ...",863,"[{'close': '2200', 'day': 1, 'open': '1600'}, ...",Metrograph,0.983868,9.5,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,56dc9292cd10833075c12b7f,"[{'id': 13065, 'name': 'Restaurant', 'icon': {...",985,"[{'close': '1300', 'day': 1, 'open': '1000'}, ...",Ludlow House,0.995972,9.3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5e46e2ec5791a10008c55728,"[{'id': 13072, 'name': 'Asian Restaurant', 'ic...",390,"[{'close': '1600', 'day': 1, 'open': '1100'}, ...",Thai Diner,0.996603,9.3,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,57c169e3498e784947e307aa,"[{'id': 13072, 'name': 'Asian Restaurant', 'ic...",965,"[{'close': '1300', 'day': 1, 'open': '1200'}, ...",Fish Cheeks,0.989820,9.2,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,5d5f24ec09484500079aee00,"[{'id': 13306, 'name': 'Taco Restaurant', 'ico...",930,"[{'close': '1400', 'day': 1, 'open': '1200'}, ...",Los Tacos No 1 Church,0.998602,9.2,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
0,53506fd9498ebca706a7c170,"[{'id': 13025, 'name': 'Wine Bar', 'icon': {'p...",210,"[{'close': '2200', 'day': 1, 'open': '1700'}, ...",La Compagnie des Vins Surnaturels,0.986039,9.2,True,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,5c6c6715f709c1002cd49290,"[{'id': 13065, 'name': 'Restaurant', 'icon': {...",749,"[{'close': '1400', 'day': 1, 'open': '1200'}, ...",SUGARFISH by sushi nozawa,0.993215,9.1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,5cc4e9d0c876c8002c3010cb,"[{'id': 13352, 'name': 'Thai Restaurant', 'ico...",608,"[{'close': '2200', 'day': 1, 'open': '1700'}, ...",Wayla,0.987894,9.1,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,511c1229e4b09afd49f4bc51,"[{'id': 13009, 'name': 'Cocktail Bar', 'icon':...",690,NaN,Attaboy,0.991539,9.1,True,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN
10,613cbe71dc7b552c56e39a0a,"[{'id': 13106, 'name': 'Dim Sum Restaurant', '...",467,"[{'close': '1300', 'day': 1, 'open': '1100'}, ...",House of Joy,0.992405,9.1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN